#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=99

start() {
	echo "starting webradio"
	/www/scripts/webradio.sh &>/var/log/webradio &        
}  

stop() {
	echo "stopping webradio"
	killall webradio.sh madplay
}
